# Generated by Django 5.0 on 2026-03-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number_plate", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.IntegerField()),
                ("is_occupied", models.BooleanField(default=False)),
                ("lot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="parking.parkinglot")),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("slot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="parking.slot")),
                ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="parking.vehicle")),
            ],
        ),
    ]
